apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |-
      scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']

      # blackbox
      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [http_2xx] 
        static_configs:
        - targets:
          - http://prometheus-service:9090
          - http://grafana-service:3000
        relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter-service:9115 

      # define one separate job for each middleware to keep things clean
      - job_name: 'redis-monitoring'
        kubernetes_sd_configs:
        - role: pod   
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          regex: "9121" # the exporter's port must be 9121
          action: keep
        - source_labels: [__meta_kubernetes_pod_label_monitoring]
          action: replace
          regex: middleware_(.*)
          replacement: $1
          target_label: middleware
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: tenant
        - source_labels: [__meta_kubernetes_pod_ip]
          replacement: redis://$1:6379
          action: replace
          target_label: redis_address
      
      # Runtime pods
      - job_name: 'tenant-runtime-pod-monitoring'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_monitoring]
          action: keep
          regex: runtime_(.*)
        - source_labels: [__meta_kubernetes_pod_label_monitoring]
          action: replace
          regex: runtime_(.*)
          replacement: $1
          target_label: runtime
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: tenant
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod
        - source_labels: [__meta_kubernetes_pod_ip]
          action: replace
          target_label: kubernetes_pod_ip

      # Runtime services
      - job_name: 'tenant-runtime-service-monitoring'
        kubernetes_sd_configs:
        - role: service
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_label_monitoring]
          action: keep
          regex: runtime_(.*)
        - source_labels: [__meta_kubernetes_service_label_monitoring]
          action: replace
          regex: runtime_(.*)
          replacement: $1
          target_label: runtime
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: tenant
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_service

