---
apiVersion: v1
kind: Pod
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  serviceAccountName: prometheus
  containers:
  - name: grafana
    image: grafana/grafana
    ports:
    - containerPort: 3000
    volumeMounts:
    - name: grafana-vol
      mountPath: "/data/provisioning/datasources"
      readOnly: true
    env:
    - name: GF_PATHS_PROVISIONING
      value: "/data/provisioning"
  volumes:
  - name: grafana-vol
    projected:
      sources:
      - configMap:
          name: grafana-provision
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000