apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  serviceAccountName: prometheus
  containers:
  - name: prometheus
    image: prom/prometheus
    args:
    - --config.file=/etc/prometheus/prometheus.yml
    - --web.enable-lifecycle
    ports:
    - containerPort: 9090
    volumeMounts:
    - name: prometheus-config-vol
      mountPath: "/etc/prometheus/"
      readOnly: true
  volumes:
  - name: prometheus-config-vol
    projected:
      sources:
      - configMap:
          name: prometheus-config 
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    