apiVersion: v1
kind: Pod
metadata:
  name: redis-exporter
  labels:
    app: redis-exporter
    name: redis-exporter
  annotations:
    redis.exporter.port: "9121"
spec:
  containers:
  - name: redis-exporter
    image: oliver006/redis_exporter
    ports:
    - containerPort: 9121
    env:
    - name: REDIS_ADDR
      value: "redis://100.96.1.4:6379,redis://100.96.1.5:6379,redis://100.96.2.5:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter-service
spec:
  selector:
    name: redis-exporter
  ports:
  - name: exporter
    protocol: TCP
    port: 9121
    targetPort: 9121