apiVersion: v1
kind: Pod
metadata:
  name: redis-2
  labels:
    app: redis
    name: redis-2
  annotations:
    redis.exporter.port: "9121"
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 6379
  - name: redis-exporter
    image: oliver006/redis_exporter
    ports:
    - containerPort: 9121
    env:
    - name: REDIS_ADDR
      value: "redis://redis-2:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-2-service
spec:
  selector:
    name: redis-2
  ports:
  - name: redis
    protocol: TCP
    port: 26379
    targetPort: 6379
  - name: exporter
    protocol: TCP
    port: 29121
    targetPort: 9121